FROM node:22-alpine AS base

WORKDIR /app

RUN npm install -g pnpm

FROM base AS development
COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile
COPY . .

EXPOSE 8080

CMD ["pnpm", "run", "start:debug"]
